### ISSUE TITLE
Cannot find module provided via tsd

### ISSUE THREAD

**Issue by ColinEberhardt** [palantir/tslint#826]
In my project I am using tsd to add redux. I import it like so:

```
import { createStore } from 'redux';
```

My TypeScript compiler is happy because I added the type definition file to the `files` property of `tsconfig.json`:

```
{
  ...
  "files": [
    "typings/redux/redux.d.ts",
    "src/bootstrap.ts"
  ]
}
```

However, when I run my build, tslint is failing:

```
[15:52:52] Starting 'tslint'...
[15:52:52] Starting 'clean'...
[15:52:52] Finished 'clean' after 228 ms
[15:52:52] Starting 'compile'...
[15:52:52] Starting 'copy:libs'...
[15:52:52] Starting 'copy:assets'...
[15:52:52] Finished 'tslint' after 407 ms
src/store/todoStore.ts(1,29): error TS2307: Cannot find module 'redux'.
[15:52:54] TypeScript: 1 semantic error
[15:52:54] TypeScript: emit succeeded (with errors)
[15:52:54] Finished 'copy:libs' after 2.18 s
[15:52:54] Finished 'copy:assets' after 2.18 s
[15:52:54] Finished 'compile' after 2.2 s
[15:52:54] Starting 'build'...
[15:52:54] Finished 'build' after 7.26 μs
[15:52:54] Starting 'buildAndReload'...
```

I presume I have to tell tslint about this module - but I cannot find any way to do that? Is it possible to point tslint at the `tsconfig.json` file?

**Comment by JKillian** [comment]
@ColinEberhardt What does your tslint task took like? And what version of tslint are you using?

In the future there will be a way to lint via tsconfig.json - see https://github.com/palantir/tslint/issues/692

**Comment by ColinEberhardt** [comment]
Thanks @JKillian - I've pushed the code I am working on to this branch:

https://github.com/ColinEberhardt/angular2-todo/tree/redux

gulp-tslint 3.6.0, which brings in tslint 2.5.1

The tslint task is here: https://github.com/ColinEberhardt/angular2-todo/blob/redux/gulpfile.js#L51

**Comment by ColinEberhardt** [comment]
I'll try running talent directly over my code to see if it is a version issues

**Comment by ColinEberhardt** [comment]
Heh, autocorrect... Talent = tslint:-)

**Comment by ColinEberhardt** [comment]
Running command line tslint on the offending file works with both tslint 2.5.1 and 3.0.0:

> tslint src/store/todoStore.ts

Odd.

**Comment by JKillian** [comment]
`error TS2307: Cannot find module 'redux'.` seems very much like an error TypeScript would throw and not one TSLint would produce. (It's possible the TypeScript libraries used inside tslint are producing the error though.) I thought maybe the code was getting built by TypeScript with only the source files but not the typings file inside your `tslint` task, but it doesn't look like that.

**Comment by adidahiya** [comment]
@ColinEberhardt That is a TypeScript error, not a TSLint error. You can tell because it has an error code "TS####" and says `TypeScript: 1 semantic error`.

TSLint errors look more like this:

```
src/rules/preferConstRule.ts[73, 40]: missing semicolon
```

**Comment by JKillian** [comment]
@ColinEberhardt Yep, think this is coming from the compile step - if you run `gulp tslint` do you see the error? I'm guessing you'll see it when you run `gulp compile`
