### PR TITLE
Internalized isPrivateIdentifier helper

### LINKED ISSUE #4929: TSLint 6.1 requires TS 3.8 to compile
unintentional breaking change caused by https://github.com/palantir/tslint/pull/4915

`ts.PrivateIdentifier` should not be referenced as a type because it leads to build failures like this in TS 3.7:

```
$ tsc -p ./src

../../node_modules/tslint/lib/language/utils.d.ts:159:72 - error TS2694: Namespace 'ts' has no exported member 'PrivateIdentifier'.

159 export declare function isPrivateIdentifier(node: ts.Node): node is ts.PrivateIdentifier;

                                                                           ~~~~~~~~~~~~~~~~~
```

https://app.circleci.com/pipelines/github/palantir/blueprint/30/workflows/8eef41b7-2728-43c5-9121-70a3105bace4/jobs/31261/parallel-runs/0/steps/0-104

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
#### PR checklist

- [x] Addresses an existing issue: fixes #4929
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [ ] Documentation update

#### Overview of change:

Moving it into just the file that uses it fixes the issue of it being exported in the public `.d.ts` files.

#### CHANGELOG.md entry:

[bugfix] Internalized isPrivateIdentifier to fix TS<3.8 compiles

### CODE REVIEW

File: src/rules/noUnnecessaryQualifierRule.ts [hunk 1]
```diff
@@ -152,3 +152,9 @@ function tryGetAliasedSymbol(symbol: ts.Symbol, checker: ts.TypeChecker): ts.Sym
         ? checker.getAliasedSymbol(symbol)
         : undefined;
 }
+
+/** Wrapper for compatability with typescript@<3.8.2 */
+export function isPrivateIdentifier(node: ts.Node): node is ts.PrivateIdentifier {
```
Comment (adidahiya) [inline src/rules/noUnnecessaryQualifierRule.ts:157]: this works, but if you remove the `export`, the rule will be truly backwards compatible (the reference to `ts.PrivateIdentifier` will be elided from typings)

```suggestion
function isPrivateIdentifier(node: ts.Node): node is ts.PrivateIdentifier {
```
