### ISSUE TITLE
typescript peer dependency to low for successful compilation

### ISSUE THREAD

**Issue by eps1lon** [palantir/tslint#4106]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 2.1.6
- __Running TSLint via__: Node.js API

TSLint cannot be used programmatically in a typescript project with `typescript<2.3.0` despite peerDependencies listing `typescript >= 2.1.0` i.e. writing a rule for TSLint with `typescript@~2.1.0` results in a compilation error:
 ```bash
node_modules/tslint/lib/language/utils.d.ts(52,57): error TS1005: ',' expected.
node_modules/tslint/lib/language/utils.d.ts(52,61): error TS1005: ',' expected.
```

Cause of this is https://github.com/palantir/tslint/blob/9b7574bce3b912d9ec71c9cf374b7d0423b0bb80/src/language/utils.ts#L106
Generic argument defaults where added in [typescript 2.3](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generic-parameter-defaults).

Unfortunately this method is part of the public API which might cause trouble if we remove the default. Removing this default results in a successful build with 2.1.

Repro: [eps1lon/tslint-issue-typescript-peer-version](https://github.com/eps1lon/tslint-issue-typescript-peer-version)
