### ISSUE TITLE
[ordered-imports] TypeScript 2.0.0: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by zaggino** [palantir/tslint#1457]
### Bug Report
- **TSLint version**: `3.14.0-dev.1`
- **TypeScript version**: `2.0.0`
- **Running TSLint via**: https://github.com/zaggino/brackets-typescript/blob/master/src/node/ts-utils.ts#L270-L284

Getting error deep in syntaxWalker when trying to run linter (doesn't seem to matter what the linted code is):

```
TSLint failure: TypeError: Cannot read property 'text' of undefined
  at Object.getTokenPosOfNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:5283:71)
  at NodeObject.getStart (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:52058:23)
  at OrderedImportsWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\rules\orderedImportsRule.js:92:33)
  at C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
  at visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:7947:20)
  at Object.forEachChild (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:8107:21)
  at OrderedImportsWalker.SyntaxWalker.walkChildren (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
  at OrderedImportsWalker.SyntaxWalker.visitConditionalExpression (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:52:14)
  at OrderedImportsWalker.SyntaxWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:273:22)
  at OrderedImportsWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\rules\orderedImportsRule.js:98:36)
  at C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
  at visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:7947:20)
  at Object.forEachChild (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:8007:21)
  at OrderedImportsWalker.SyntaxWalker.walkChildren (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
  at OrderedImportsWalker.SyntaxWalker.visitVariableDeclaration (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:217:14)
  at OrderedImportsWalker.SyntaxWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:441:22)
  at OrderedImportsWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\rules\orderedImportsRule.js:98:36)
  at C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
  at visitEachNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:7959:30)
  at Object.forEachChild (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:8124:24)
  at OrderedImportsWalker.SyntaxWalker.walkChildren (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
  at OrderedImportsWalker.SyntaxWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:453:22)
  at OrderedImportsWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\rules\orderedImportsRule.js:98:36)
  at C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
  at visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:7947:20)
  at Object.forEachChild (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:8122:21)
  at OrderedImportsWalker.SyntaxWalker.walkChildren (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
  at OrderedImportsWalker.SyntaxWalker.visitVariableStatement (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:220:14)
  at OrderedImportsWalker.SyntaxWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:444:22)
  at OrderedImportsWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\rules\orderedImportsRule.js:98:36)
  at C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
  at visitEachNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:7959:30)
  at Object.forEachChild (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:8115:24)
  at OrderedImportsWalker.SyntaxWalker.walkChildren (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
  at OrderedImportsWalker.SyntaxWalker.visitBlock (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:28:14)
  at OrderedImportsWalker.SyntaxWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:249:22)
  at OrderedImportsWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\rules\orderedImportsRule.js:98:36)
  at C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
  at visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:7947:20)
  at Object.forEachChild (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:8035:21)
  at OrderedImportsWalker.SyntaxWalker.walkChildren (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
  at OrderedImportsWalker.SyntaxWalker.visitFunctionDeclaration (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:94:14)
  at OrderedImportsWalker.SyntaxWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:315:22)
  at OrderedImportsWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\rules\orderedImportsRule.js:98:36)
  at C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
  at visitEachNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:7959:30)
  at Object.forEachChild (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\typescript\lib\typescript.js:8117:24)
  at OrderedImportsWalker.SyntaxWalker.walkChildren (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
  at OrderedImportsWalker.SyntaxWalker.visitSourceFile (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:190:14)
  at OrderedImportsWalker.SyntaxWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:414:22)
  at OrderedImportsWalker.visitNode (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\rules\orderedImportsRule.js:98:36)
  at OrderedImportsWalker.SyntaxWalker.walk (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\walker\syntaxWalker.js:7:14)
  at Rule.AbstractRule.applyWithWalker (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\language\rule\abstractRule.js:19:16)
  at Rule.apply (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\rules\orderedImportsRule.js:15:21)
  at Linter.lint (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\tslint\lib\tslint.js:65:37)
  at _getDiagnostics (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\dist\node\ts-utils.js:240:40)
  at tryCatcher (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\util.js:16:23)
  at Promise._settlePromiseFromHandler (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:504:31)
  at Promise._settlePromise (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:561:18)
  at Promise._settlePromise0 (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:606:10)
  at Promise._settlePromises (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:685:18)
  at Promise._fulfill (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:630:18)
  at Promise._resolveCallback (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:425:57)
  at Promise._settlePromiseFromHandler (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:516:17)
  at Promise._settlePromise (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:561:18)
  at Promise._settlePromise0 (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:606:10)
  at Promise._settlePromises (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:685:18)
  at Promise._fulfill (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:630:18)
  at PromiseArray._resolve (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise_array.js:125:19)
  at PromiseArray._promiseFulfilled (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise_array.js:143:14)
  at Promise._settlePromise (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:566:26)
  at Promise._settlePromise0 (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:606:10)
  at Promise._settlePromises (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\promise.js:685:18)
  at Async._drainQueue (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\async.js:138:16)
  at Async._drainQueues (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\async.js:148:10)
  at Async.drainQueues (C:\Users\Zaggi\AppData\Roaming\Brackets\extensions\user\brackets-typescript\node_modules\bluebird\js\release\async.js:17:14)
  at process._tickCallback (node.js:415:13)
```

**Comment by JKillian** [comment]
Hmm, not sure about the root cause of this one. Can you duplicate the bug when running TSLint from the CLI?

**Comment by zaggino** [comment]
@JKillian it's a weird one, played with it a bit and:
1) doesn't replicate from CLI
2) doesn't replicate when I remove the program argument gained from `languageService.getProgram()`
3) weirdest one: it only replicates on first run, if I run it twice, I get results just fine even using program from `languageService.getProgram()`

**Comment by JKillian** [comment]
That is weird! Just to check, are you using the `--type-check` when testing the CLI? Passing a `program` argument essentially does the same thing as using that CLI flag

**Comment by zaggino** [comment]
Yep, no issues using: `$ ./node_modules/.bin/tslint --type-check -c tslint.json src/node/ts-utils.ts`
I'll try to investigate what changes in the program that second run passes fine.

**Comment by zaggino** [comment]
So... the problem is not fixed on second attempt, but on an attempt made a while after the languageService is first constructed. This would indicate that something inside TypeScript or TSLint is loading asynchronously? Is there such a thing?

**Comment by JKillian** [comment]
Just a sidenote (my mistake here):

```
$ ./node_modules/.bin/tslint --type-check -c tslint.json --project tsconfig.json
```

is most likely the actual command you want. This'll lint all the code in your project and is probably most similar to what your original code was doing.

**Comment by JKillian** [comment]
Not sure about the async issue - it seems strange that there'd be a delay like that, if so the TS API would take some sort of completion callback I'd assume.

**Comment by zaggino** [comment]
So, just an update... I've rewritten my implementation of `ts.LanguageServiceHost` (https://github.com/zaggino/brackets-typescript/blob/master/src/node/language-service-host.ts) and now I can replicate it consistently, but only on some of the files ... will need to figure out what's the difference between them. It's not an async issue definitely.

**Comment by zaggino** [comment]
So debugging it's this line:
https://github.com/palantir/tslint/blob/master/src/rules/orderedImportsRule.ts#L147

It will fail when `node.kind === 53` which is `SyntaxKind.QuestionToken`

Doing this https://github.com/zaggino/brackets-typescript/commit/236504ccbaac71e29dface27cb3041da9b41fb7f will make the file pass rule `ordered-imports`

**Comment by JKillian** [comment]
Strange, having trouble seeing why that line 147 would cause an issue. Going to cc @danvk who wrote this rule and see if anything seems off to him.

**Comment by danvk** [comment]
I'm having trouble reproducing this.

```
$ cd tslint
$ git pull
$ npm install typescript@2.0.0
$ tsc --version
Version 2.0.0
$ npm run test
### Fast Compile >>src/test/utils.ts
Using tsc v2.0.0
src/language/utils.ts(27,11): error TS2322: Type '{ fileExists: () => boolean; getCanonicalFileName: (filename: string) => string; getCurrentDirect...' is not assignable to type 'CompilerHost'.
  Property 'getDirectories' is missing in type '{ fileExists: () => boolean; getCanonicalFileName: (filename: string) => string; getCurrentDirect...'.
src/test.ts(63,19): error TS2322: Type '{ fileExists: () => boolean; getCanonicalFileName: (filename: string) => string; getCurrentDirect...' is not assignable to type 'CompilerHost'.
  Property 'getDirectories' is missing in type '{ fileExists: () => boolean; getCanonicalFileName: (filename: string) => string; getCurrentDirect...'.
src/tslint.ts(62,62): error TS2345: Argument of type '{ readDirectory: (path: string, extensions?: string[], exclude?: string[], include?: string[]) =>...' is not assignable to parameter of type 'ParseConfigHost'.
  Property 'useCaseSensitiveFileNames' is missing in type '{ readDirectory: (path: string, extensions?: string[], exclude?: string[], include?: string[]) =>...'.
```

Is there a version of tslint that builds with 2.0.0?

**Comment by JKillian** [comment]
Yep! Grab `tslint@next` and it'll work correctly with TS 2.x

**Comment by danvk** [comment]
I still can't reproduce.

I did `git checkout origin/next` and pasted this snippet into `test/rules/ordered-imports/lowercase-first/test.ts.lint`:

```ts
export function mapLintResultFailures(failures): Array<CodeInspectionError> {
  return failures ? failures.map(failure => {
    return {
      type: 'problem_type_warning',
      message: failure.failure + ' [' + failure.ruleName + ']',
      pos: {
        line: failure.startPosition.lineAndCharacter.line,
        ch: failure.startPosition.lineAndCharacter.character
      }
    };
  }) : [];
}
```

but the tests still pass without that error. If there's a snippet that makes it break, I'd be happy to debug.

**Comment by JKillian** [comment]
Hmm @zaggino, are you able to come up with any easy minimally reproducible versions of the bug? Perhaps it's something with an old version of the `typescript` package in the pipeline somewhere?

**Comment by zaggino** [comment]
@JKillian @danvk sorry guys, seems like some glitch that's not easily replicable, I've tried simplier stuff but this is the best I can do:
```
git clone https://github.com/zaggino/brackets-typescript.git tslint-1457 -b tslint-1457 && cd tslint-1457
npm install
node test.js
```
on my node `6.3.1` this outputs as:
```
$ node test.js

checking src/node/domain.ts
tsDiagnostics errors: 0
tsLint errors: 1
 C:/dev/tslint-1457/src/node/domain.ts[5, 24]: Named imports must be alphabetized.


checking src/node/language-service-host.ts
tsDiagnostics errors: 0
C:\dev\tslint-1457\node_modules\typescript\lib\typescript.js:5283
        return ts.skipTrivia((sourceFile || getSourceFileOfNode(node)).text, node.pos);
                                                                      ^

TypeError: Cannot read property 'text' of undefined
    at Object.getTokenPosOfNode (C:\dev\tslint-1457\node_modules\typescript\lib\typescript.js:5283:71)
    at NodeObject.getStart (C:\dev\tslint-1457\node_modules\typescript\lib\typescript.js:52058:23)
    at OrderedImportsWalker.visitNode (C:\dev\tslint-1457\node_modules\tslint\lib\rules\orderedImportsRule.js:92:33)
    at C:\dev\tslint-1457\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:63
    at visitNode (C:\dev\tslint-1457\node_modules\typescript\lib\typescript.js:7947:20)
    at Object.forEachChild (C:\dev\tslint-1457\node_modules\typescript\lib\typescript.js:8107:21)
    at OrderedImportsWalker.SyntaxWalker.walkChildren (C:\dev\tslint-1457\node_modules\tslint\lib\language\walker\syntaxWalker.js:459:12)
    at OrderedImportsWalker.SyntaxWalker.visitConditionalExpression (C:\dev\tslint-1457\node_modules\tslint\lib\language\walker\syntaxWalker.js:52:14)
    at OrderedImportsWalker.SyntaxWalker.visitNode (C:\dev\tslint-1457\node_modules\tslint\lib\language\walker\syntaxWalker.js:273:22)
    at OrderedImportsWalker.visitNode (C:\dev\tslint-1457\node_modules\tslint\lib\rules\orderedImportsRule.js:98:36)
```
It tests two files, first one is without any ternanry if's (question marks), second one is with them.

**Comment by DanielKucal** [comment]
```
TypeError: Cannot read property 'text' of undefined
    at ExpressionCallMetadataWalker.validateCallExpression (/Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/noForwardRefRule.js:58:73)
    at ExpressionCallMetadataWalker.visitCallExpression (/Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/noForwardRefRule.js:44:14)
    at ExpressionCallMetadataWalker.SyntaxWalker.visitNode (/Users/danielkucal/Applications/Angular2/tslint/lib/language/walker/syntaxWalker.js:305:22)
    at /Users/danielkucal/Applications/Angular2/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/danielkucal/Applications/Angular2/tslint/node_modules/typescript/lib/typescript.js:11899:24)
    at Object.forEachChild (/Users/danielkucal/Applications/Angular2/tslint/node_modules/typescript/lib/typescript.js:11963:21)
    at ExpressionCallMetadataWalker.SyntaxWalker.walkChildren (/Users/danielkucal/Applications/Angular2/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at ExpressionCallMetadataWalker.SyntaxWalker.visitPropertyAssignment (/Users/danielkucal/Applications/Angular2/tslint/lib/language/walker/syntaxWalker.js:210:14)
    at ExpressionCallMetadataWalker.SyntaxWalker.visitNode (/Users/danielkucal/Applications/Angular2/tslint/lib/language/walker/syntaxWalker.js:464:22)
    at /Users/danielkucal/Applications/Angular2/tslint/lib/language/walker/syntaxWalker.js:535:63
TypeError: Cannot read property 'text' of undefined
    at /Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/noAttributeParameterDecoratorRule.js:55:35
    at /Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/util/function.js:26:59
    at Maybe.bind (/Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/util/function.js:21:20)
    at Maybe.fmap (/Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/util/function.js:26:21)
    at /Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/noAttributeParameterDecoratorRule.js:50:14
    at Object.validate (/Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/walkerFactory/walkerFn.js:18:82)
    at /Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/walkerFactory/walkerFn.js:53:27
    at Array.forEach (native)
    at class_1.visitNode (/Users/danielkucal/Applications/Angular2/zoomsphere2-web/node_modules/codelyzer/walkerFactory/walkerFn.js:51:28)
    at /Users/danielkucal/Applications/Angular2/tslint/lib/language/walker/syntaxWalker.js:535:63
```
I'm getting similar errors while using `npm link`ed tslint... Any idea?

**Comment by ajafff** [comment]
@DanielKucal This has nothing to do with the original issue. The stack trace is completely different.
Also note that the failure is located in a third party rule of the `codelyzer` package. The maintainer(s) of that package are probably a bigger help.

**Comment by DanielKucal** [comment]
@ajafff okay, thanks!
