### ISSUE TITLE
TSLint 6.1 requires TS 3.8 to compile

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#4929]
unintentional breaking change caused by https://github.com/palantir/tslint/pull/4915

`ts.PrivateIdentifier` should not be referenced as a type because it leads to build failures like this in TS 3.7:

```
$ tsc -p ./src

../../node_modules/tslint/lib/language/utils.d.ts:159:72 - error TS2694: Namespace 'ts' has no exported member 'PrivateIdentifier'.

159 export declare function isPrivateIdentifier(node: ts.Node): node is ts.PrivateIdentifier;

                                                                           ~~~~~~~~~~~~~~~~~
```

https://app.circleci.com/pipelines/github/palantir/blueprint/30/workflows/8eef41b7-2728-43c5-9121-70a3105bace4/jobs/31261/parallel-runs/0/steps/0-104

**Comment by JoshuaKGoldberg** [comment]
Interesting. Maybe we should add a CI build task that type-checks the `lib` `.d.ts` files to avoid this in the future?

**Comment by rrdelaney** [comment]
Should it be possible to build TSLint with older TypeScript versions? My assumptions with #4915 was that TSLint should run against older versions, but being built with the latest was OK.

**Comment by JoshuaKGoldberg** [comment]
Ah, the issue here is that if someone is running `tsc` in an earlier version than 3.8 on a repository that includes `tslint` in its `node-modules/`, the `ts.PrivateIdentifier` will break type checking.

I didn't consider this when reviewing the PR and can send a quick fix to move the `isPrivateIdentifier` function into the file it's used.

For folks reading this issue, you could also enable [TypeScript's `--skipLibCheck`](https://stackoverflow.com/questions/52311779/usage-of-the-typescript-compiler-argument-skiplibcheck) to disable these errors. But we'll release a new version so you don't have to. 👍

**Comment by JoshuaKGoldberg** [comment]
🤖 Beep boop! 👉  **TSLint is deprecated** 👈  and you should **switch to [typescript-eslint](https://typescript-eslint.io)**! 🤖 

🔒 This issue is being locked to prevent further unnecessary discussions. Thank you! 👋
