### ISSUE TITLE
Custom Rule doesn't work - tsc doesn't compile with TypeScript 2.0.10

### ISSUE THREAD

**Issue by dhardtke** [palantir/tslint#2103]
### Bug Report

- __TSLint version__: `4.3.0`
- __TypeScript version__: `2.0.10`
- __Running TSLint via__: CLI

#### TypeScript code being linted
None

#### Actual behavior
```
tsc --noImplicitAny noImportsRule.ts
node_modules/tslint/lib/configuration.d.ts(14,38): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/tslint/lib/language/utils.d.ts(39,82): error TS2305: Module 'ts' has no exported member 'ModifierFlags'.
node_modules/tslint/lib/language/utils.d.ts(48,84): error TS2305: Module 'ts' has no exported member 'ObjectFlags'.
```

#### Expected behavior
A successful compilation

#### Additional Information
I guess it has to do with typescript 2.0.10.

**Comment by dhardtke** [comment]
This apparently is related to my global TypeScript installation.
Using `tsc` from node_modules works like a charm:
> .\node_modules\.bin\tsc authorTagRequiredRule.ts
